import {
  NbActionsModule,
  NbAlertModule,
  NbButtonModule,
  NbCardModule,
  NbCheckboxModule,
  NbDatepickerModule,
  NbFormFieldModule,
  NbIconModule,
  NbInputModule, NbListModule,
  NbMenuModule,
  NbRadioModule,
  NbRouteTabsetModule,
  NbSearchModule,
  NbSelectModule,
  NbSpinnerModule,
  NbTabsetModule,
  NbTimepickerModule,
  NbTreeGridModule,
  NbUserModule,
} from '@nebular/theme';
import { Ng2SmartTableModule } from 'ng2-smart-table';

export const NB_MODULES = [
  NbActionsModule,
  NbButtonModule,
  NbCheckboxModule,
  NbDatepickerModule,
  NbInputModule,
  NbRadioModule,
  NbSelectModule,
  NbUserModule,
  Ng2SmartTableModule,
  NbMenuModule,
  NbCardModule,
  NbTreeGridModule,
  NbIconModule,
  NbTimepickerModule,
  NbRouteTabsetModule,
  NbSpinnerModule,
  NbSearchModule,
  NbFormFieldModule,
  NbAlertModule,
  NbTabsetModule,
  NbListModule,
];
